"""message_is_seed_flag

Revision ID: 1a11430b62b9
Revises: b0e866329b4c
Create Date: 2026-07-25 21:55:36.555065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a11430b62b9'
down_revision: Union[str, Sequence[str], None] = 'b0e866329b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default="false" bat buoc: bang messages da co du lieu (714 dong o dev
    # luc viet migration nay) - them cot NOT NULL khong default se loi vi cac dong
    # cu khong co gia tri.
    op.add_column('messages', sa.Column('is_seed', sa.Boolean(),
                  server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_seed')
    # ### end Alembic commands ###
