"""add expertise_notes to users

Revision ID: 2fd8baf43c21
Revises: 6b7e1058ae67
Create Date: 2026-08-09 18:45:50.412249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd8baf43c21'
down_revision: Union[str, Sequence[str], None] = '6b7e1058ae67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expertise_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expertise_notes')
    # ### end Alembic commands ###
