"""usage_log_hardening_fields

Revision ID: 79191abc9937
Revises: a7c1e5d90b23
Create Date: 2026-07-22 17:28:19.986559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79191abc9937'
down_revision: Union[str, Sequence[str], None] = 'a7c1e5d90b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default bat buoc: bang usage_log da co du lieu that (Phase 0-2 eval) —
    # them cot NOT NULL khong default se loi tren Postgres voi bang khong rong.
    op.add_column('usage_log', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('usage_log', sa.Column('feature', sa.String(length=32), nullable=False,
                                         server_default='chat'))
    op.add_column('usage_log', sa.Column('status', sa.String(length=32), nullable=False,
                                         server_default=''))
    op.add_column('usage_log', sa.Column('latency_ms', sa.Integer(), nullable=False,
                                         server_default='0'))
    op.add_column('usage_log', sa.Column('tool_call_count', sa.Integer(), nullable=False,
                                         server_default='0'))
    op.add_column('usage_log', sa.Column('iteration', sa.Integer(), nullable=False,
                                         server_default='0'))
    op.add_column('usage_log', sa.Column('estimated_cost', sa.Float(), nullable=False,
                                         server_default='0'))
    op.create_foreign_key(None, 'usage_log', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_log', type_='foreignkey')
    op.drop_column('usage_log', 'estimated_cost')
    op.drop_column('usage_log', 'iteration')
    op.drop_column('usage_log', 'tool_call_count')
    op.drop_column('usage_log', 'latency_ms')
    op.drop_column('usage_log', 'status')
    op.drop_column('usage_log', 'feature')
    op.drop_column('usage_log', 'user_id')
    # ### end Alembic commands ###
