"""message_is_ack_flag

Revision ID: 8193d5d974a1
Revises: 9aecbe52fa05
Create Date: 2026-07-24 10:23:00.621559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8193d5d974a1'
down_revision: Union[str, Sequence[str], None] = '9aecbe52fa05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('messages', sa.Column('is_ack', sa.Boolean(), nullable=False,
                                        server_default='false'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_ack')
    # ### end Alembic commands ###
