"""session_model_rolling_summary

Revision ID: b0e866329b4c
Revises: 8193d5d974a1
Create Date: 2026-07-24 12:30:15.848417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e866329b4c'
down_revision: Union[str, Sequence[str], None] = '8193d5d974a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('rolling_summary', sa.Text(), server_default='', nullable=False))
    op.add_column('conversations', sa.Column('summary_through_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'archived_at')
    op.drop_column('conversations', 'summary_through_at')
    op.drop_column('conversations', 'rolling_summary')
    # ### end Alembic commands ###
