"""directives_table

Revision ID: de06a77534d4
Revises: 79191abc9937
Create Date: 2026-07-22 21:34:21.674061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de06a77534d4'
down_revision: Union[str, Sequence[str], None] = '79191abc9937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('verbatim_text', sa.Text(), nullable=False),
    sa.Column('structured_summary', sa.Text(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('sent', 'seen', 'acked', 'question', 'renegotiate', 'done', 'cancelled', name='directivestatus'), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('remind_count', sa.Integer(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directives_recipient_id'), 'directives', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_directives_workspace_id'), 'directives', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directives_workspace_id'), table_name='directives')
    op.drop_index(op.f('ix_directives_recipient_id'), table_name='directives')
    op.drop_table('directives')
    # ### end Alembic commands ###
